<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BOMC9082093.local" ignored="1" name="Test2" tests="1" failures="1" timestamp="2021-03-04T22:17:45 COT" time="2.016" errors="0">
  <testcase name="@AfterMethod afterMethod" time="2.008" classname="com.com.bancodebogota.test.Prueba1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.com.bancodebogota.test.Prueba1.afterMethod(Prueba1.java:89)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="f2" time="0.001" classname="com.com.bancodebogota.test.Prueba1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.com.bancodebogota.test.Prueba1.f2(Prueba1.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- f2 -->
  <testcase name="f1" time="0.0" classname="com.com.bancodebogota.test.Prueba1">
    <ignored/>
  </testcase> <!-- f1 -->
</testsuite> <!-- Test2 -->
